MAINTAINER "info@bielkorpus.com"
NAME "%displayName%"
INFOHREF "%infoHref%"
PATH "%name%"
ENCODING "UTF-8"
LANGUAGE "Belarusian"
#SUBCDEF "/corpora/%name%/subcorpora"

PATH   '/corpora/%name%/indexed/'
VERTICAL  '/corpora/%name%/%name%.vert'



ATTRIBUTE   word {
	LABEL "слова"
}

ATTRIBUTE   lemma {
	LABEL "лема"
}

ATTRIBUTE   pos {
	LABEL "часьціна мовы"
}

ATTRIBUTE   properness {
	LABEL "уласнасьць"
}

ATTRIBUTE   animacy {
	LABEL "адушаўлёнасьць"
}

ATTRIBUTE   personalness {
	LABEL "асабовасьць"
}

ATTRIBUTE   abbreviation {
	LABEL "скарачэньне"
}

ATTRIBUTE   gender {
	LABEL "род"
}

ATTRIBUTE   declension {
	LABEL "скланеньне"
}

ATTRIBUTE   case {
	LABEL "склон"
}

ATTRIBUTE   number {
	LABEL "лік"
}

ATTRIBUTE   adjective_type {
	LABEL "тып"
}

ATTRIBUTE   degree {
	LABEL "ступень"
}

ATTRIBUTE   adjective_adverb {
	LABEL "у форме прыслоўя"
}

ATTRIBUTE   inflection_type {
	LABEL "словазьмяненьне"
}

ATTRIBUTE   meaning {
	LABEL "значэньне"
}

ATTRIBUTE   form {
	LABEL "форма"
}

ATTRIBUTE   indeclinable {
	LABEL "нескланяльны"
}

ATTRIBUTE   category {
	LABEL "разрад"
}

ATTRIBUTE   person {
	LABEL "асоба"
}

ATTRIBUTE   transitivity {
	LABEL "пераходнасьць"
}

ATTRIBUTE   aspect {
	LABEL "трываньне"
}

ATTRIBUTE   reflexivity {
	LABEL "зваротнасьць"
}

ATTRIBUTE   conjugation_type {
	LABEL "спражэньне"
}

ATTRIBUTE   tense {
	LABEL "час"
}

ATTRIBUTE   gerund {
	LABEL "дзеепрыслоўе"
}

ATTRIBUTE   voice {
	LABEL "стан"
}

ATTRIBUTE   short_form {
	LABEL "кароткая форма"
}

ATTRIBUTE   formation_source {
	LABEL "спосаб утварэньня"
}

ATTRIBUTE   conjunction_type {
	LABEL "тып"
}

ATTRIBUTE   error_type {
	LABEL "тып памылкі"
}


ATTRIBUTE   lc {
	LABEL	"word (lowercase)"
	DYNAMIC  utf8lowercase
	DYNLIB   internal
	ARG1     "C"
	FUNTYPE  s
	FROMATTR word
	TYPE     index
	TRANSQUERY	yes
}

ATTRIBUTE   lemma_lc {
	LABEL	"lemma (lowercase)"
	DYNAMIC  utf8lowercase
	DYNLIB   internal
	ARG1     "C"
	FUNTYPE  s
	FROMATTR lemma
	TYPE     index
	TRANSQUERY	yes
}

STRUCTURE doc {
	ATTRIBUTE n {
		LABEL "Нумар"
	}
	ATTRIBUTE title {
		LABEL "Назва"
	}
#	ATTRIBUTE author {
#		LABEL "Аўтар"
#	}
	ATTRIBUTE publication_date {
		LABEL "Год публікацыі"
	}
	ATTRIBUTE url {
		LABEL "Url"
	}
	ATTRIBUTE type {
		LABEL "Тып"
	}
	ATTRIBUTE style {
		LABEL "Стыль"
	}
#	ATTRIBUTE subcorpus {
#		LABEL "Падкорпус"
#	}
}

STRUCTATTRLIST "doc.n,doc.title,doc.publication_date,doc.url,doc.type,doc.style"
SHORTREF "=doc.n"

STRUCTURE s {
	DISPLAYTAG 0
}
STRUCTURE p {
	DISPLAYTAG 0
}

STRUCTURE g {
	DISPLAYTAG 0
	DISPLAYBEGIN "_EMPTY_"
}

